import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import "bootstrap-icons/font/bootstrap-icons.min.css"; // Import bootstrap icons CSS
import 'react-quill/dist/quill.snow.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ImportBsJS from "./lib/importBsJS";
import SideBar from "./components/sidebar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Smarter Grocy',
  description: 'Generated by create Klupps Team',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImportBsJS></ImportBsJS>
        <SideBar>
          {children}
        </SideBar>
      </body>
    </html>
  )
}
